/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_init.c
**     Project     : Blinky3_KL03Z
**     Processor   : MKL03Z32VFK4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-09-13, 10:44, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_init
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL03Z32FK4
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  SE0 - Single-ended channel 0           : <Automatic>
**                  SE1 - Single-ended channel 1           : <Automatic>
**                  SE2 - Single-ended channel 2           : <Automatic>
**                  SE3 - Single-ended channel 3           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDD
**                  Voltage reference low                  : VSS
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN2 - Input 2                          : <Automatic>
**                  IN3 - Input 3                          : <Automatic>
**                  IN5 - Input 5                          : <Automatic>
**                  OUT - Output                           : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  CLK - Clock                            : <Automatic>
**                  DIO - Data input/output                : <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DWT                        : 
**              Peripheral Type FGPIO                      : 
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 8                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 9                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 12                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 10                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 11                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 13                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P4 - Wake-up pin 4                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  ALT0 - Pulse counter input 0           : <Automatic>
**                  ALT1 - Pulse counter input 1           : <Automatic>
**                  ALT2 - Pulse counter input 2           : <Automatic>
**                  ALT3 - Pulse counter input 3           : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type LPUART                     : 
**                Custom name                              : LPUART0
**                LPUART0                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART0                             : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC
**                OSC                                      : 
**                  External clock/Oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC                                 : yes
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type RFSYS                      : 
**                Custom name                              : RFSYS
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  CLKIN - Clock input                    : <Automatic>
**                  CLKOUT - Oscillator output             : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Trace clock output                     : <Automatic>
**                  ERCLK32K clock output                  : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD
**                  Chip ground                            : VSS
**                Bool_SUPPLY                              : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM1                                : yes
**              Peripheral Type VREF                       : 
**                Custom name                              : VREF
**                VREF                                     : 
**                  OUT - Voltage reference output         : <Automatic>
**                Bool_VREF                                : yes
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTB6/IRQ_2/LPTMR0_ALT3/TPM1_CH1/TPM_CLKIN1: 
**                Custom name, Signal name                 : TOUCH_B/J1_4
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 2: PTB7/IRQ_3/TPM1_CH0                 : 
**                Custom name, Signal name                 : TOUCH_A/J1_6
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 3: VDD                                 : 
**                Custom name, Signal name                 : VDD
**              Pin 4: VSS                                 : 
**                Custom name, Signal name                 : VSS
**              Pin 5: EXTAL0/PTA3/I2C0_SCL/I2C0_SDA/LPUART0_TX: 
**                Custom name, Signal name                 : EXTAL
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 6: XTAL0/PTA4/I2C0_SDA/I2C0_SCL/LPUART0_RX/CLKOUT: 
**                Custom name, Signal name                 : XTAL
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 7: PTA5/RTC_CLKIN/TPM0_CH1/SPI0_SS_b   : 
**                Custom name, Signal name                 : J2_3
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 8: PTA6/TPM0_CH0/SPI0_MISO             : 
**                Custom name, Signal name                 : J2_5
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 9: PTB10/TPM0_CH1/SPI0_SS_b            : 
**                Custom name, Signal name                 : LED_RED/J2_1
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 10: PTB11/TPM0_CH0/SPI0_MISO           : 
**                Custom name, Signal name                 : LED_GREEN/J2_2
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 11: PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI     : 
**                Custom name, Signal name                 : J2_4
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 12: ADC0_SE9/PTB0/IRQ_5/LLWU_P4/EXTRG_IN/SPI0_SCK/I2C0_SCL: 
**                Custom name, Signal name                 : BUTTON_SW2/J2_6
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 13: ADC0_SE8/CMP0_IN3/PTB1/IRQ_6/LPUART0_TX/LPUART0_RX/I2C0_SDA: 
**                Custom name, Signal name                 : OPENSDA_TX/J1_2
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 14: VREF_OUT/CMP0_IN5/PTB2/IRQ_7/LPUART0_RX/LPUART0_TX: 
**                Custom name, Signal name                 : OPENSDA_RX/J1_1
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 15: ADC0_SE3/PTA8/I2C0_SCL/SPI0_MOSI   : 
**                Custom name, Signal name                 : THER_P/J4_2
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 16: ADC0_SE2/PTA9/I2C0_SDA/SPI0_SCK    : 
**                Custom name, Signal name                 : THER_N/J4_1
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 17: PTB3/IRQ_10/I2C0_SCL/LPUART0_TX    : 
**                Custom name, Signal name                 : ACCEL_SCL/J2_10
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 18: PTB4/IRQ_11/I2C0_SDA/LPUART0_RX    : 
**                Custom name, Signal name                 : ACCEL_SDA/J2_9
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 19: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b: 
**                Custom name, Signal name                 : BUTTON_SW3/J1_7
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 20: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0/CLKOUT: 
**                Custom name, Signal name                 : ACCEL_INT/J4_3
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 21: PTB13/CLKOUT32K/TPM1_CH1/RTC_CLKOUT: 
**                Custom name, Signal name                 : LED_BLUE/J4_5
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 22: ADC0_SE15/CMP0_IN2/PTA0/IRQ_0/LLWU_P7/TPM1_CH0/SWD_CLK: 
**                Custom name, Signal name                 : SWD_CLK/J1_8
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 23: PTA1/IRQ_1/LPTMR0_ALT1/TPM_CLKIN0/RESET_b: 
**                Custom name, Signal name                 : RESET/BUTTON_SW1/J3_3
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 24: PTA2/CMP0_OUT/SWD_DIO              : 
**                Custom name, Signal name                 : SWD_DIO/J4_4
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              HAL fsl_mcglite_hal                        : fsl_mcglite_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_init.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_init_module pin_init module documentation
**  @{
*/         

/* MODULE pin_init. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_init.h"



/*FUNCTION**********************************************************************
*
* Function Name : init_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_coredebug_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt3);
  /* Affects PORTA_PCR2 register */
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt3);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_coredebug_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOB_IDX:                     /* GPIOB_IDX */
      /* Affects PORTB_PCR10 register */
      PORT_HAL_SetMuxMode(PORTB,10UL,kPortMuxAsGpio);
      /* Affects PORTB_PCR11 register */
      PORT_HAL_SetMuxMode(PORTB,11UL,kPortMuxAsGpio);
      /* Affects PORTB_PCR13 register */
      PORT_HAL_SetMuxMode(PORTB,13UL,kPortMuxAsGpio);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOB_IDX:                     /* GPIOB_IDX */
      PORT_HAL_SetMuxMode(PORTB,10UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTB,11UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTB,13UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}

/*FUNCTION**********************************************************************
*
* Function Name : init_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_osc_pins(uint32_t instance)
{
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
  /* Affects PORTA_PCR4 register */
  PORT_HAL_SetMuxMode(PORTA,4UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_osc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,4UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rcm_pins(uint32_t instance)
{
  /* Affects PORTA_PCR1 register */
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt3);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rcm_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_sim_pins
* Description   : SIM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_sim_pins(uint32_t instance)
{
  /* Affects PORTB_PCR13 register */
  PORT_HAL_SetMuxMode(PORTB,13UL,kPortMuxAsGpio);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_sim_pins
* Description   : SIM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_sim_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTB,13UL,kPortPinDisabled);
}


/* END pin_init. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
